# Build pipeline to validate install-script and ARM templates used for deployment
# on a continuous basis while changing them.
# Future-plan: attempt to run quick tests on ACI instances for the scripts

trigger:
- master

stages:
- stage: buildvalidate
  displayName: 'Validating templates & scripts'
  jobs:
  - job: buildvalidatejob
    displayName: 'Validating and verifying...'
    continueOnError: false
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: devops/azure-pipelines-build.yml
      parameters:
        pSubscriptionId: '$(param.DevSubscription)'
        pVpnDnsName: '$(param.DevVpnDnsName)'
        pVpnCaCertPubEncoded: '$(param.DevCaCertPub)'
        pRgNamePrefix: '$(param.DevRgPrefix)'
        pStorageAccount: '$(param.DevStorageAccount)'
        pAdminUserName: '$(param.DevAdminUserName)'
        pAdminUserPassword: '$(param.DevAdminUserPassword)'
        pAdminUserSshPubKey: '$(param.DevAdminUserSshPubKey)'
        pVnetName: '$(param.DevVnetName)'
        pVnetSubnetId: '$(param.DevVnetsubnetId)'
