#
# Used to at least ensure basic quality of the bash and powershell scripts committed to the repository
#

name: CI

# Executed whenever something gets pushed to the repository or when a pull-request gets started
on:
  push:
    branches: [ master ]
    paths:
      - '**.sh'
      - '**.ps1'
      - '!**.md'
      - '!winterminalcfg/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**.sh'
      - '**.ps1'
      - '!**.md'
      - '!winterminalcfg/**'

# The workflow validates the basic PowerShell and Bash syntax as the min-bar baseline
jobs:
  validate-scripts:
    name: Validate PowerShell and Bash scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Validate the PowerShell Script
    - name: Validating Install-WindowsMachine.ps1
      uses: docker://github/super-linter:v2.2.0