#
# Used to at least ensure basic quality of the bash and powershell scripts committed to the repository
#

name: CI

# Executed whenever something gets pushed to the repository or when a pull-request gets started
on:
  push:
    branches: [ master ]
    paths:
      - '**.sh'
      - '**.ps1'
      - '!**.md'
      - '!winterminalcfg/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**.sh'
      - '**.ps1'
      - '!**.md'
      - '!winterminalcfg/**'

# The workflow validates the basic PowerShell and Bash syntax as the min-bar baseline
jobs:
  validate-scripts:
    name: Validate PowerShell and Bash scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Validate the PowerShell and Bash Scripts
    # PowerShell deactived for now as PS linter in super-linter has a bug
    # https://github.com/github/super-linter/issues/279
    - name: Validating PowerShell and Bash scripts
      uses: docker://github/super-linter:v3
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_ANSIBLE: false
        VALIDATE_ARM: false
        VALIDATE_BASH: true
        VALIDATE_BASH_EXEC: true
        VALIDATE_CLOJURE: false
        VALIDATE_CLOUDFORMATION: false
        VALIDATE_COFFEE: false
        VALIDATE_CSHARP: false
        VALIDATE_CSS: false
        VALIDATE_DART: false
        VALIDATE_DOCKERFILE: false
        VALIDATE_DOCKERFILE_HADOLINT: false
        VALIDATE_EDITORCONFIG: false
        VALIDATE_ENV: false
        VALIDATE_GO: false
        VALIDATE_GROOVY: false
        VALIDATE_HTML: false
        VALIDATE_JAVA: false
        VALIDATE_JAVASCRIPT_ES: false
        VALIDATE_JAVASCRIPT_STANDARD: false
        VALIDATE_JSON: false
        VALIDATE_JSX: false
        VALIDATE_KOTLIN: false
        VALIDATE_KUBERNETES_KUBEVAL: false
        VALIDATE_LATEX: false
        VALIDATE_LUA: false
        VALIDATE_MD: false
        VALIDATE_OPENAPI: false
        VALIDATE_PERL: false
        VALIDATE_PHP: false
        VALIDATE_PHP_BUILTIN: false
        VALIDATE_PHP_PHPCS: false
        VALIDATE_PHP_PHPSTAN: false
        VALIDATE_PHP_PSALM: false
        VALIDATE_PROTOBUF: false
        VALIDATE_PYTHON: false
        VALIDATE_PYTHON_PYLINT: false
        VALIDATE_PYTHON_FLAKE8: false
        VALIDATE_PYTHON_BLACK: false
        VALIDATE_POWERSHELL: true
        VALIDATE_R: false
        VALIDATE_RAKU: false
        VALIDATE_RUBY: false
        VALIDATE_SHELL_SHFMT: false
        VALIDATE_SNAKEMAKE_LINT: false
        VALIDATE_SNAKEMAKE_SNAKEFMT: false
        VALIDATE_STATES: false
        VALIDATE_SQL: false
        VALIDATE_TERRAFORM: false
        VALIDATE_TERRAFORM_TERRASCAN: false
        VALIDATE_TSX: false
        VALIDATE_TYPESCRIPT_ES: false
        VALIDATE_TYPESCRIPT_STANDARD: false
        VALIDATE_XML: false
        VALIDATE_YAML: false
        VALIDATE_CONFIG_FILE: false
